[project]
name = "apriori-algorithm-groceries"
version = "0.1.0"
requires-python = ">=3.9,<3.11"

dependencies = [
  "streamlit==1.31.1",
  "pandas==1.5.3",
  "mlxtend==0.23.1",
  "matplotlib==3.7.2",
  "networkx==3.1",
  "openpyxl==3.1.2",
  "joblib==1.3.2"
]
